### ISSUE TITLE
Temperature sensor should use temperature union element

### ISSUE THREAD

**Issue by rob-mclean** [STMicroelectronics/STMems_Android_Sensor_HAL_IIO#8]
This may be overly picky, but...

In the file src/Temp.cpp, in the ProcessData method, the sensor_event should use the "temperature" union element to pass data into the pipe instead of the "relative_humidity" element.

Because the sensor_event member is a union, and because both the "temperature" and "relative_humidity" elements are of the same type in the union, I don't think this error affects the HAL performance.  However, it is an obvious copy and change mistake that was missed when the class was coded.  It may lead to confusion (as it did for me), or it may cause the HAL Temp class stop working correctly if AOSP changes the sensor_event_t structure so that those elements are no longer part of a union.

**Comment by mariotesi** [comment]
This project has been discontinued because of the Android Treble requirements which led to pass-through mode deprecation and new requirements for using HIDL / AIDL interfaces.
As highlighted in the project repository entry page [About](https://github.com/STMicroelectronics/STMems_Android_Sensor_HAL_IIO) the current Sensors HAL can be found in this repository [st-mems-android-linux-sensors-hal](https://github.com/STMicroelectronics/st-mems-android-linux-sensors-hal/)
